# Generated by Django 4.2.4 on 2023-08-08 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('email', models.EmailField(max_length=100)),
                ('number', models.IntegerField(max_length=15)),
                ('city', models.CharField(max_length=180)),
            ],
        ),
    ]
